all:
  vars:
    ansible_user: debian
    repository: 'https://github.com/ambanum/ima-graph-generator.git'
    nb_processors: '1'
    ansible_host: 51.89.231.68
    branch: 'main'
  children:
    preprod:
      hosts:
        preproduction:
          branch: 'develop'
          directory: 'ima-graph-generator-preproduction'
          port: '7832'
          env_directory: '.env.preproduction'
    prod:
      hosts:
        production:
          directory: 'ima-graph-generator-production'
          port: '7032'
          env_directory: '.env.production'
        tflmi-production:
          directory: 'ima-graph-generator-tflmi-production'
          port: '7034'
          env_directory: '.env.tflmi.production'
        ambnum-production:
          directory: 'ima-graph-generator-ambnum-production'
          port: '7036'
          env_directory: '.env.ambnum.production'
